name: Generate Snake

on:
  schedule:
    # Chạy tự động mỗi 24 giờ
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          # github user name to read the contribution graph from (**required**)
          # using action context var `github.repository_owner` or specified user
          github_user_name: ${{ github.repository_owner }}

          # list of files to generate.
          # one file per line. Each output can be customized with options as query string.
          #
          #  supported options:
          #  - palette:     build-in palettes: github, github-dark, github-light
          #  - color_snake: color of the snake
          #  - color_dots:  color of the dots separated by comma [empty] [github] [github-dark] [github-light]
          #  - dark:        dark mode color [empty] [github] [github-dark] [github-light]
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to Output Branch
        uses: crazy-max/github-action-push-assets@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          base_dir: dist
          commit_message: "Update Snake Animation"
